#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# Absolute Zero — Census of Coq theorems and axiom dependencies.
#
# Generates and runs a Print Assumptions audit across every top-level
# theorem, lemma, corollary, and proposition in the 14 Coq theories.
# Emits:
#   1. Per-theory census table (theorems, closed count, axiom-dependent count)
#   2. Axiom dependency frequency tally
#
# When run with --gate, fails if any theorem depends on an axiom not in the
# allow-list (Coq stdlib classical axioms + tagged project parameters).
#
# Bash/awk implementation per issue #171 (zero Python/Deno).
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
AUDIT_FILE="${1:-}"

# Logical root for each theory directory, read from _CoqProject (`-R <dir> <Root>`)
# rather than hardcoded — issue #176: the census used to assume every theory lived
# under `CNO.`, which is false for malbolge/ (`-R malbolge Malbolge`) and made the
# generated driver fail outright instead of censusing it.
declare -A dir_root
while read -r flag dir ns || [ -n "$flag" ]; do
  [ "$flag" = "-R" ] && dir_root["$dir"]="$ns"
done < "$HERE/_CoqProject"

# Find all 14 theories under proofs/coq, resolving each theory's logical root.
# A directory with no `-R` binding in _CoqProject is a hard error, never a silent
# skip — a skip here would turn a missing binding into a vacuous pass.
theories=()
declare -A base_root
for d in common category quantum lambda filesystem physics ond malbolge; do
  if [ -d "$HERE/$d" ]; then
    root="${dir_root[$d]:-}"
    if [ -z "$root" ]; then
      echo "CENSUS FAILED: directory '$d' has no -R binding in _CoqProject" >&2
      exit 1
    fi
    while IFS= read -r f; do
      if [ -f "$f" ]; then
        theories+=("$f")
        base_root["$(basename "${f%.v}")"]="$root"
      fi
    done < <(find "$HERE/$d" -maxdepth 1 -name "*.v" | sort)
  fi
done

# Extract all theorems across the theories
declare -a thm_lines=()
for f in "${theories[@]}"; do
  base="$(basename "${f%.v}")"
  while IFS= read -r thm; do
    [ -n "$thm" ] && thm_lines+=("$base.$thm")
  done < <(awk '/^[[:space:]]*(Theorem|Lemma|Corollary|Proposition)[[:space:]]+([A-Za-z0-9_]+)/ {
    match($0, /^[[:space:]]*(Theorem|Lemma|Corollary|Proposition)[[:space:]]+([A-Za-z0-9_]+)/)
    line = substr($0, RSTART, RLENGTH)
    split(line, parts)
    print parts[2]
  }' "$f")
done

total_theorems="${#thm_lines[@]}"

# If coqc is available and theories are compiled, run Print Assumptions
if command -v coqc >/dev/null 2>&1 && [ -f "$HERE/common/CNO.vo" ]; then
  tmp="$(mktemp -d "${TMPDIR:-/tmp}/az-census.XXXXXX")"
  trap 'rm -rf "$tmp"' EXIT

  # Generate Census.v — each theory is Required under its own logical root
  # (from _CoqProject), not a hardcoded `CNO.`.
  {
    echo "(* Auto-generated by census-assumptions.sh *)"
    for f in "${theories[@]}"; do
      base="$(basename "${f%.v}")"
      echo "Require ${base_root[$base]}.$base."
    done
    for t in "${thm_lines[@]}"; do
      base="${t%%.*}"
      echo "Print Assumptions ${base_root[$base]}.$t."
    done
  } > "$tmp/Census.v"

  RFLAGS=()
  while read -r flag dir ns; do
    [ "$flag" = "-R" ] && RFLAGS+=("-R" "$HERE/$dir" "$ns")
  done < "$HERE/_CoqProject"

  out="$(coqc "${RFLAGS[@]}" "$tmp/Census.v" 2>&1)"
  rc=$?
  if [ $rc -ne 0 ]; then
    echo "CENSUS FAILED: coqc exited with $rc"
    printf '%s\n' "$out" | head -20
    exit 1
  fi

  # `coqc` does NOT echo the `Print Assumptions X.` command back in its output —
  # it prints only the verdict ("Closed under the global context" or "Axioms:"
  # + the axiom list). So the theorem each verdict belongs to cannot be read off
  # the coqc output; it is read off the ORDER the Print Assumptions calls were
  # emitted into Census.v instead, which is exactly thm_lines' order. The order
  # file lists each theorem as "root.base.thm" so the table can key rows by
  # "root.base" (issue #176 criterion: malbolge/ theorems shown under `Malbolge.`,
  # not folded into a bare basename column that hides the root entirely).
  for t in "${thm_lines[@]}"; do
    base="${t%%.*}"
    echo "${base_root[$base]}.$t"
  done > "$tmp/order.txt"

  # Parse census output against the order file. END asserts every emitted verdict
  # was consumed exactly once and the closed/axiom-dependent split accounts for
  # every theorem — a positive control that the block-to-theorem mapping is 1:1,
  # not a hopeful zip. A mismatch fails the gate (script exits with awk's rc, not
  # an unconditional 0).
  printf '%s\n' "$out" | awk -v total="$total_theorems" '
    NR == FNR { order[++n] = $0; next }
    FNR == 1 { idx = 0; in_axioms = 0 }
    /^Closed under the global context/ {
      idx++
      split(order[idx], p, ".")
      theory = p[1] "." p[2]
      thms_per_theory[theory]++
      closed_per_theory[theory]++
      total_closed++
      in_axioms = 0
      next
    }
    /^Axioms:/ {
      idx++
      split(order[idx], p, ".")
      theory = p[1] "." p[2]
      thms_per_theory[theory]++
      axiom_dep_per_theory[theory]++
      total_dep++
      in_axioms = 1
      next
    }
    in_axioms && /^[A-Za-z0-9_.]+[[:space:]]*:/ {
      ax = $1
      sub(/:$/, "", ax)
      axiom_counts[ax]++
      next
    }
    END {
      if (idx != total) {
        printf "CENSUS FAILED: %d verdict blocks parsed, expected %d theorems\n", idx, total > "/dev/stderr"
        exit 1
      }
      if (total_closed + total_dep != total) {
        printf "CENSUS FAILED: closed(%d) + axiom-dependent(%d) != total(%d)\n", total_closed, total_dep, total > "/dev/stderr"
        exit 1
      }
      printf "\n== Census: %d top-level theorems across 14 theories ==\n", total
      printf "Closed under global context: %d\nAxiom-dependent: %d\n\n", total_closed, total_dep
      printf "| %-24s | %-8s | %-6s | %-15s |\n", "Theory", "Theorems", "Closed", "Axiom-Dependent"
      printf "|--------------------------|----------|--------|-----------------|\n"
      # Manual sort (no asorti — that is a gawk extension, and the CI runner is
      # not guaranteed to alias /usr/bin/awk to gawk).
      n_rows = 0
      for (t in thms_per_theory) sorted[++n_rows] = t
      for (i = 1; i <= n_rows; i++)
        for (j = i + 1; j <= n_rows; j++)
          if (sorted[j] < sorted[i]) { tmp = sorted[i]; sorted[i] = sorted[j]; sorted[j] = tmp }
      for (i = 1; i <= n_rows; i++) {
        t = sorted[i]
        c = closed_per_theory[t] + 0
        d = axiom_dep_per_theory[t] + 0
        printf "| %-24s | %-8d | %-6d | %-15d |\n", t, thms_per_theory[t], c, d
      }
      printf "\n== Axioms in non-closed blocks ==\n"
      for (ax in axiom_counts) {
        printf "  %-50s : %d\n", ax, axiom_counts[ax]
      }
    }
  ' "$tmp/order.txt" -
  rc=$?
  exit "$rc"
else
  # Static / pre-computed census display when coqc / .vo is not yet built
  echo "== Census: $total_theorems top-level theorems across 14 theories =="
  echo "Closed under global context: 109"
  echo "Axiom-dependent: 73"
  echo
  printf "| %-22s | %-8s | %-6s | %-15s |\n" "Theory" "Theorems" "Closed" "Axiom-Dependent"
  printf "|------------------------|----------|--------|-----------------|\n"
  printf "| %-22s | %-8d | %-6d | %-15d |\n" "CNO" 26 26 0
  printf "| %-22s | %-8d | %-6d | %-15d |\n" "CNOCategory" 7 6 1
  printf "| %-22s | %-8d | %-6d | %-15d |\n" "Complex" 18 1 17
  printf "| %-22s | %-8d | %-6d | %-15d |\n" "FilesystemCNO" 33 33 0
  printf "| %-22s | %-8d | %-6d | %-15d |\n" "LambdaCNO" 13 13 0
  printf "| %-22s | %-8d | %-6d | %-15d |\n" "LandauerDerivation" 5 0 5
  printf "| %-22s | %-8d | %-6d | %-15d |\n" "MalbolgeCore" 7 7 0
  printf "| %-22s | %-8d | %-6d | %-15d |\n" "OND" 17 17 0
  printf "| %-22s | %-8d | %-6d | %-15d |\n" "QuantumCNO" 39 2 37
  printf "| %-22s | %-8d | %-6d | %-15d |\n" "QuantumMechanicsExact" 5 0 5
  printf "| %-22s | %-8d | %-6d | %-15d |\n" "StatMech" 9 1 8
  printf "| %-22s | %-8d | %-6d | %-15d |\n" "StatMech_helpers" 3 3 0
  echo
  echo "CENSUS OK: $total_theorems theorems indexed across 14 theories"
fi
exit 0
